baseurl = "https://carmelolg.github.io/lagambanese"

title = "Lagambanese"
theme = "soho"

languageCode = "en"
DefaultContentLanguage = "it"

enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]

[params]
title = "Lagambanese"
description = "Football Hattrick Club"

images = ["images/logo.png"]
profilePicture = "images/logo.png"

copyright = "carmelolg"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

builtWith = true
mainSections = ["post"]

## Set custom theme color.


#1D3557 blu scuro
#457B9D blu chiaro
#A8DADC azzurrino
#F1FAEE grigio chiaro verde
#E63946 rosso acceso
#f0a00c giallo   

themeColor = "#1D3557"

[[params.socialIcons]]
icon = "fas fa-futbol"
title = "Hattrick"
url = "https://www88.hattrick.org/Club/?TeamID=727740"


[menu]

  [[menu.main]]
  name = "Storia"
  identifier = "about"
  weight = 1
  url = "/about/"

  [[menu.main]]
  name = "Comunicati stampa"
  weight = 2
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Albo d'oro"
  weight = 3
  identifier = "stats"
  url = "/stats/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4